-- 코드를 입력하세요

# 1. 2022-01 책들을 찾아서 저자별로 분류 
# 2. 1에서 만든 테이블에서 저자별로, 카테고리별로  묶어서 새로운 테이블을 만들고
SELECT A.AUTHOR_ID,
    A.AUTHOR_NAME,
    SUB.CATEGORY,
    SUM(SUB.SALES * SUB.PRICE) AS TOTAL_SALSES
FROM AUTHOR A
JOIN
    (SELECT S.BOOK_ID, S.SALES_DATE, S.SALES, B.PRICE, B.CATEGORY, B.AUTHOR_ID 
    FROM BOOK_SALES S
    JOIN BOOK B
     ON S.BOOK_ID = B.BOOK_ID
    WHERE S.SALES_DATE LIKE "2022-01-%") AS SUB
ON SUB.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, SUB.CATEGORY
ORDER BY A.AUTHOR_ID ASC, SUB.CATEGORY DESC;
