-- 코드를 입력하세요

# BOOK_ID별 기간내 총 판매량 
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
    SUM(SUB.TOTAL * B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A 
ON B.AUTHOR_ID = A.AUTHOR_ID 
JOIN 
    (SELECT BOOK_ID, SUM(SALES) AS TOTAL
    FROM BOOK_SALES
    WHERE "2022-01-01" <= SALES_DATE AND SALES_DATE < "2022-02-01"
    GROUP BY BOOK_ID) AS SUB
ON B.BOOK_ID = SUB.BOOK_ID
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;
