-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN 
    (SELECT PARENT.ITEM_ID, CHILD.PARENT_ITEM_ID 
    FROM ITEM_INFO PARENT
    LEFT JOIN ITEM_TREE CHILD
    ON PARENT.ITEM_ID = CHILD.PARENT_ITEM_ID) AS SUB
ON SUB.ITEM_ID = I.ITEM_ID
WHERE SUB.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC;