# 세단, suv
# 2022-11-01 ~ 2022-11-30 대여가능 

# 30일간의 대여 금액이 50만원 이상 200만원 미만

SELECT C.CAR_ID,
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE
    AND D.DURATION_TYPE = "30일 이상"
WHERE 1=1
    AND C.CAR_TYPE IN ('세단', 'SUV') 
    AND C.CAR_ID NOT IN (
        # 대여 불가능한 CAR_ID 
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (END_DATE < "2022-11-01" OR START_DATE > "2022-11-30")
    ) 
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;



    

