

WITH SUB AS (
    SELECT H.HISTORY_ID, 
        C.CAR_TYPE, 
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS D 
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)


SELECT SUB.HISTORY_ID,
    FLOOR(SUB.DAILY_FEE * SUB.D * ((100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100)) AS FEE

FROM SUB
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON SUB.CAR_TYPE = P.CAR_TYPE
    AND P.DURATION_TYPE = (
    CASE 
        WHEN SUB.D >= 90 THEN '90일 이상'
        WHEN SUB.D >= 30 THEN '30일 이상'
        WHEN SUB.D >= 7 THEN '7일 이상'
        ELSE NULL
    END 
    )
ORDER BY FEE DESC, SUB.HISTORY_ID DESC;



