
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR) AS SUB
ON F.FLAVOR = SUB.FLAVOR
ORDER BY F.TOTAL_ORDER + SUB.TOTAL DESC
LIMIT 3;


