-- 코드를 작성해주세요
SELECT E.EMP_NO, E.EMP_NAME,
    CASE 
        WHEN SUM(G.SCORE) / 2 < 80 THEN "C"
        WHEN SUM(G.SCORE) / 2 < 90 THEN "B"
        WHEN SUM(G.SCORE) / 2 < 96 THEN "A"
        ELSE "S"
    END AS GRADE,
    CASE
        WHEN SUM(G.SCORE) / 2 < 80 THEN 0
        WHEN SUM(G.SCORE) / 2 < 90 THEN E.SAL * 0.1
        WHEN SUM(G.SCORE) / 2 < 96 THEN E.SAL * 0.15
        ELSE E.SAL * 0.2
    END AS BONUS
FROM HR_EMPLOYEES E
JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
ORDER BY E.EMP_NO;
    
