WITH M AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT P.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R
ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM M
    WHERE CNT = (SELECT MAX(CNT) FROM M)
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;


