-- 코드를 입력하세요
SELECT DISTINCT(C.CAR_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE (C.CAR_TYPE = '세단') AND
    ('2022-10-01' <= START_DATE AND START_DATE < '2022-11-01')
    
ORDER BY CAR_ID DESC;
