WITH M AS (
    SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO)

SELECT M.SUM_SCORE AS SCORE,
    M.EMP_NO, 
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM M
JOIN HR_EMPLOYEES E
ON M.EMP_NO = E.EMP_NO
WHERE SUM_SCORE = (SELECT MAX(SUM_SCORE) FROM M)

# 2020002	181