WITH MAX_V AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)


SELECT P.CATEGORY, P.PRICE AS MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P
JOIN MAX_V M
ON P.PRICE = M.MAX_PRICE AND P.CATEGORY = M.CATEGORY
ORDER BY MAX_PRICE DESC;
