-- 코드를 입력하세요
# 카테고리별 최대 가격을 찾아
WITH SUB AS (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY)
    
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN SUB S
ON (F.PRICE = S.PRICE) AND (F.CATEGORY = S.CATEGORY)
ORDER BY F.PRICE DESC;